mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include, url
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from users.views import UserUpdateView, UserDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.start, name='start'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('profile/update/', UserUpdateView.as_view(), name='profile-update'),
    path('profile/delete/', UserDeleteView.as_view(), name='profile-delete'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^tree/', include('tree.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/tree/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse

from person import views
from person.view_check import relation_check
from person.view_history import PersonDetailView
from person.views import (PersonCreateView, PersonUpdateView,
                          PersonDeleteView, RelationCreateView, RelationListView,
                          RelationDeleteView)
from .view_stats import HomeView, ChartData, ChartDataAge, ChartDataName
from .views import (
    FamilyTreeAllListView,
    FamilyTreeDetailView,
    FamilyTreeCreateView,
    FamilyTreeUpdateView,
    FamilyTreeDeleteView,
)

urlpatterns = [
    # ===================tree
    path('all/', FamilyTreeAllListView.as_view(), name='tree-all'),
    path('new/', FamilyTreeCreateView.as_view(), name='tree-create'),
    path('<int:pk>/', FamilyTreeDetailView.as_view(), name='tree-detail'),
    path('<int:pk>/update/', FamilyTreeUpdateView.as_view(), name='tree-update'),
    path('<int:pk>/delete/', FamilyTreeDeleteView.as_view(), name='tree-delete'),
    # ======================stats
    path('<int:pk>/stats/', HomeView.as_view(), name='tree-stats'),
    path('<int:pk>/stats/chart/', ChartData.as_view(), name='stats-chart'),
    path('<int:pk>/stats/chart_age/', ChartDataAge.as_view(), name='stats-chart-age'),
    path('<int:pk>/stats/chart_name/', ChartDataName.as_view(), name='stats-chart-name'),
    # =======================relation
    path('<int:pk>/new_related/', RelationCreateView.as_view(), name='relation-create'),
    path('<int:pk>/check_rel/', relation_check, name='relation-check'),
    path('<int:pk>/list_rel/', RelationListView.as_view(), name='relation-list'),
    path('<int:pk>/list_rel/<int:pk_rel>/delete/', RelationDeleteView.as_view(), name='relation-delete'),
    # =========================person
    path('<int:pk>/new/', PersonCreateView.as_view(), name='person-create'),
    path('<int:pk>/<int:pk_per>/', PersonDetailView.as_view(), name='person-detail'),
    path('<int:pk>/<int:pk_per>/update/', PersonUpdateView.as_view(), name='person-update'),
    path('<int:pk>/<int:pk_per>/delete/', PersonDeleteView.as_view(), name='person-delete'),
    path('new_related/load_person', views.load_person, name='load_people'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/person/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from mysite import settings
from tree.models import FamilyTree


# YEARS = [tuple([x, x]) for x in range(timezone.now().year,1902,-1)]


class Person(models.Model):
    class Sex(models.IntegerChoices):
        MALE = 0, _('Male')
        FEMALE = 1, _('Female')

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    maiden_name = models.CharField(max_length=30, null=True, blank=True)
    sex = models.IntegerField(choices=Sex.choices, default=0)
    date_of_birth = models.DateField(default=None, null=True, blank=True)
    date_of_death = models.DateField(default=None, null=True, blank=True)
    datetime_person = models.DateTimeField(default=timezone.now)
    family_tree = models.ForeignKey(FamilyTree, on_delete=models.CASCADE, related_name='family_tree')

    def __str__(self):
        if self.maiden_name is not None:
            return "%s %s (%s) %s" % (self.first_name, self.last_name, self.maiden_name, self.get_age())
        return "%s %s %s" % (self.first_name, self.last_name, self.get_age())

    def get_absolute_url(self):
        return reverse('person-detail', kwargs={'pk': self.family_tree_id, 'pk_per': self.id})

    def get_age(self):
        living = self.date_of_birth.__format__('%d/%m/%Y') if self.date_of_birth is not None else '-'
        death = self.date_of_death.__format__('%d/%m/%Y') if self.date_of_death is not None else '-'
        if living == '-' and death == '-':
            return ''
        return f'[{living} - {death}]'


class Relation(models.Model):
    class FamilyRelation(models.TextChoices):
        ANCESTOR = 'A', _('Ancestor')
        PARTNER = 'P', _('Partner')
        DESCENDANT = 'D', _('Descendant')

    source_person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='source_person')
    related_person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='related_person')
    datetime_relation = models.DateTimeField(default=timezone.now)
    family_relation = models.CharField(max_length=10, choices=FamilyRelation.choices, default='D')
    date_beginning = models.DateField(default=None, null=True, blank=True)
    date_end = models.DateField(default=None, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('tree-detail', kwargs={'pk': Person.objects.get(id=self.source_person_id).family_tree_id})

mysite/person/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from person.models import Person, Relation
from tree.models import FamilyTree
from .forms import PersonForm, RelationForm, FilterForm


class PersonCreateView(UserPassesTestMixin, LoginRequiredMixin, CreateView):
    model = Person
    template_name = 'person/form.html'
    form_class = PersonForm

    def form_valid(self, form):
        person = form.instance
        tree = FamilyTree(owner=self.request.user, id=self.kwargs['pk'])
        person.family_tree = tree
        person.save()
        return super(PersonCreateView, self).form_valid(form)

    def get_object(self):
        obj = get_object_or_404(Person, pk=self.kwargs.get('pk_per'))
        # obj = super(PersonCreateView, self).get_object()
        obj.datetime_person = timezone.now()
        obj.save()
        return obj

    def test_func(self):
        tree = self.kwargs['pk']
        tree = FamilyTree.objects.get(id=tree)
        if self.request.user == tree.owner:
            return True
        return False


class PersonUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Person
    template_name = 'person/update.html'
    form_class = PersonForm

    def form_valid(self, form):
        person = form.instance
        tree = FamilyTree(owner=self.request.user, id=self.kwargs['pk'])
        person.family_tree = tree
        person.save()
        return super(PersonUpdateView, self).form_valid(form)

    def test_func(self):
        person = self.get_object()
        tree = person.family_tree
        if self.request.user == tree.owner:
            return True
        return False

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Person, pk=self.kwargs.get('pk_per'))
        # obj = Person.objects.get(id=self.kwargs.get('pk_per'))
        obj.datetime_person = timezone.now()
        obj.save()
        return obj


class PersonDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Person
    template_name = 'person/confirm_delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('tree-detail', kwargs={'pk': self.object.family_tree_id})

    def test_func(self):
        person = self.get_object()
        tree = person.family_tree
        if self.request.user == tree.owner:
            return True
        return False

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Person, pk=self.kwargs.get('pk_per'))
        obj.datetime_person = timezone.now()
        obj.save()
        return obj


class RelationCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Relation
    template_name = 'relation/form.html'
    form_class = RelationForm

    def form_valid(self, form):
        relation = form.instance

        if relation.family_relation == 'D':
            swap = relation.source_person
            relation.source_person = relation.related_person
            relation.related_person = swap
            relation.family_relation = 'A'

        sex_per = Person.objects.get(id=relation.source_person_id).sex
        if relation.family_relation == 'P' and sex_per == 1:
            swap = relation.source_person
            relation.source_person = relation.related_person
            relation.related_person = swap

        if relation.date_end is None:
            if relation.related_person.date_of_death is not None and relation.source_person.date_of_death is not None:
                relation.date_end = relation.source_person.date_of_death if relation.source_person.date_of_death < relation.related_person.date_of_death else relation.related_person.date_of_death
            elif relation.source_person.date_of_death is not None:
                relation.date_end = relation.source_person.date_of_death
            elif relation.related_person.date_of_death is not None:
                relation.date_end = relation.related_person.date_of_death

        if relation.family_relation == 'A':
            birth_date = relation.related_person.date_of_birth
            if birth_date is not None:
                relation.date_beginning = birth_date

        if form.cleaned_data['merge_child_father']:
            children_rel = Relation.objects.filter(source_person=relation.source_person, family_relation='A')

            for child_rel in children_rel:
                child = child_rel.related_person
                if relation.related_person.date_of_birth and child.date_of_birth and relation.related_person.date_of_birth >= child.date_of_birth:
                    continue
                elif relation.related_person.date_of_death and child.date_of_birth and relation.related_person.date_of_death < child.date_of_birth:
                    continue
                elif Relation.objects.filter(source_person=relation.related_person, related_person=child,
                                             family_relation='A').exists():
                    continue
                child_rel.id = None
                child_rel.source_person = relation.related_person
                child_rel.save()
        if form.cleaned_data['merge_child_mother']:
            children_rel = Relation.objects.filter(source_person=relation.related_person, family_relation='A')

            for child_rel in children_rel:
                child = child_rel.related_person
                if relation.source_person.date_of_birth and child.date_of_birth and relation.source_person.date_of_birth >= child.date_of_birth:
                    continue
                elif relation.source_person.date_of_death and child.date_of_birth and relation.source_person.date_of_death < child.date_of_birth:
                    continue
                elif Relation.objects.filter(source_person=relation.source_person, related_person=child,
                                             family_relation='A').exists():
                    continue
                child_rel.id = None
                child_rel.source_person = relation.source_person
                child_rel.save()
        relation.save()

        return super(RelationCreateView, self).form_valid(form)

    def get_object(self):
        obj = get_object_or_404(Person, pk=self.kwargs.get('pk_per'))
        obj.datetime_relation = timezone.now()
        obj.save()
        return obj

    def test_func(self):
        tree = self.kwargs['pk']
        tree = FamilyTree.objects.get(id=tree)
        if self.request.user == tree.owner:
            return True
        return False


class RelationListView(UserPassesTestMixin, ListView):
    model = Relation
    template_name = 'relation/list.html'

    def get_queryset(self):
        id_tree = self.kwargs.get('pk')
        list_person = Person.objects.filter(family_tree_id=id_tree)
        matches = Relation.objects.none()
        for person in list_person:
            matches = matches | Relation.objects.filter(source_person=person)
        query = self.request.GET.get('search')
        if query:
            return matches.filter(
                Q(source_person__first_name__icontains=query) |
                Q(related_person__first_name__icontains=query) |
                Q(source_person__last_name__icontains=query) |
                Q(related_person__last_name__icontains=query) |
                Q(source_person__maiden_name__icontains=query) |
                Q(related_person__maiden_name__icontains=query)
            ).order_by('-datetime_relation')
        else:
            return matches.order_by('-datetime_relation')

    def get_context_data(self, **kwargs):
        context = super(RelationListView, self).get_context_data(**kwargs)
        if self.object_list:
            per = self.object_list.first().source_person
            tree_id = Person.objects.get(id=per.id).family_tree_id
            context['tree'] = FamilyTree.objects.get(id=tree_id)
        context["form"] = FilterForm(initial={
            'search': self.request.GET.get('search', ''),
        })
        context["search"] = self.request.GET.get('search')
        return context

    def test_func(self):
        tree = self.kwargs['pk']
        tree = FamilyTree.objects.get(id=tree)
        if tree.access == 0:
            return True
        if self.request.user == tree.owner:
            return True
        return False


class RelationDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Relation
    template_name = 'relation/delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('relation-list', kwargs={'pk': self.object.source_person.family_tree_id})

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Relation, pk=self.kwargs.get('pk_rel'))
        obj.datetime_relation = timezone.now()
        obj.save()
        return obj

    def test_func(self):
        relation = self.get_object()
        id_person = relation.source_person_id
        tree = Person.objects.get(id=id_person).family_tree
        if self.request.user == tree.owner:
            return True
        return False


def load_person(request):
    family = request.GET.get('family')
    people = Person.objects.filter(family_tree_id=family).order_by('first_name')

mysite/person/templates/relation/check.html
{% extends 'users/base_template.html' %}
{% load crispy_forms_tags %}
{% block base %}
<div class="container-sm my-3">
      <form method="POST" id="relForm" data-people-url="{% url 'load_people' %}" >
          {% csrf_token %}
          {{ context.form|crispy }}
            <button type="submit" class="btn btn-info">Search</button>
            {% if context.text %}<div class="alert alert-primary my-2 "><p class="px-2" id="response">{{ context.text }}</p></div>{% endif %}
      </form>
</div>
          <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
          <script>
              $(function () {
                  var pk_list = window.location.pathname.split('/');
                  var key = pk_list[2];

                  var url = $("#relForm").attr("data-people-url");

                  $.ajax({
                      url: url,
                      data: {
                          'family': key
                        },
                      success: function (data) {
                          $("#id_source_person").html(data);
                          $("#id_related_person").html(data);
                      }
                  });
              })
          </script>

{% endblock %}

mysite/person/templates/relation/delete.html
{% extends "users/base_template.html" %}
{% block base %}
<div class="jumbotron">
    <form method="POST" >
        {% csrf_token %}
        <h1 class="">Are you sure you want to delete the relation between {{object.source_person}} and {{ object.related_person }}?</h1>

        <div class="container py-3">
            <p class=""> <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a class="text-success px-5 my-auto" href="{% url 'relation-list' object.source_person.family_tree_id %}"><button type="button" class="btn btn-success">Cancel</button></a></p>
        </div>
    </form>
</div>

{% endblock %}

mysite/person/templates/relation/form.html
{% extends 'users/base_template.html' %}
{% load crispy_forms_tags %}
{% block base %}
<head>
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
</head>


    <div class="container-sm my-5">
      <h3>Create relation!</h3>
      <form method="post" id="personForm" data-people-url="{% url 'load_people' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button></form>
    </div>

          <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
              $(function() {
                var selectField = $('#id_family_relation'),
                    date_beginning = $('#id_date_beginning'),
                    date_end = $('#id_date_end'),
                    merge_child_father = $('#id_merge_child_father'),
                    merge_child_mother = $('#id_merge_child_mother');

                function toggleVerified(value) {
                    value == 'P' ? date_beginning.show() : date_beginning.hide();
                    value == 'P' ? date_end.show() : date_end.hide();
                    value == 'P' ? merge_child_father.show() : merge_child_father.hide();
                    value == 'P' ? merge_child_mother.show() : merge_child_mother.hide();
                }

                // show/hide on load based on pervious value of selectField
                toggleVerified(selectField.val());

                // show/hide on change
                selectField.change(function() {
                    toggleVerified($(this).val());
                });
            });

            $(function () {
                var pk_list = window.location.pathname.split('/');
                var key = pk_list[2];

              var url = $("#personForm").attr("data-people-url");  // get the url of the `load_cities` view
              //var familyId = $(this).val();  // get the selected country ID from the HTML input

              $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                  'family': key      // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                  $("#id_source_person").html(data);
                  $("#id_related_person").html(data);  // replace the contents of the city input with the data that came from the server
                }
              });

            });
          </script>
{%  endblock %}

mysite/person/templates/relation/list.html
{% extends 'users/base_template.html' %}
{% load crispy_forms_tags %}
{% block base %}

        <div class="container-fluid-sm my-3">
              <div class="row mx-1 my-1">
                    <div class="col-7 px-4">
                        <a class="text-light" href="{% url 'tree-detail' tree.id %}"><h4 class="font-weight-bold text-uppercase text-dark" >{{ tree.name_tree}} {% if tree.access %}(private){% endif %}</h4></a>
                        <p class="text-dark ">Description:  {{tree.description}}</p>
                    </div>
              </div>
        </div>

<div class="container-sm my-5">
    <form method="get">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-info">Search</button>
    </form>
</div>
<div class="container-fluid-sm">
  <table class="table table-dark table-striped">
      {% if object_list  %}
    <thead>
      <tr>
        <th>Source person</th>
        <th>Relation</th>
        <th>Related person</th>
        <th>Beginning</th>
        <th>The End</th>
      </tr>
    </thead>
    <tbody>
    {%  for rel in object_list %}
        <tr>
            <td><a class="text-light" href="{% url 'person-detail' tree.id rel.source_person_id%}">{{ rel.source_person }}</a></td>
            {%  if rel.family_relation == 'P' %}<td>married with </td>{% else %}<td>parent of</td>{% endif %}
            <td><a class="text-light" href="{% url 'person-detail' tree.id rel.related_person_id%}">{{ rel.related_person }}</a></td>
            {%  if rel.date_beginning %}<td>{{ rel.date_beginning|date:"Y-m-d"  }}</td>{% else %}<td></td>{% endif %}
            {%  if rel.date_end %}<td>{{ rel.date_end|date:"Y-m-d"  }}</td>{% else %}<td></td>{% endif %}
            <td><a href="{% url 'relation-delete' tree.id rel.id%}"><button class="btn btn-light">Delete</button></a></td>
        </tr>
    {% endfor %}
    </tbody>
      {% else %}
        <p class="list-group-item list-group-item-action" >{% if search %}There are no results for "{{ search }}".{% else %} You have not creataed any relation yet. {% endif %}</p>
        {% endif %}
  </table>
</div>


{% endblock %}

mysite/person/templates/relation/person_dropdown_list_options.html
<option value="">---------</option>
{% for person in people %}
<option value="{{ person.pk }}">{{ person }}</option>
{% endfor %}